# url-prediction-model
SanjayKAroraPhD@gmail.com
October 2018

## Description
This script runs url prediction with a simple train-test split.  It assumes as input a matrix of known firm urls and potential matches from MS Bing.  Variables include the search result # (i.e., rank), length of the candidate url, matches of words derived from the known firm name and name of the url, etc. 

In [25]:
# import data processing and other libraries
import csv
import sys
import requests
import re
import pprint
import pymongo
import traceback
from time import sleep
import requests
import pandas as pd
from IPython.display import display
import time
import numpy as np

In [41]:
# import sklearn
from sklearn.model_selection import train_test_split
from sklearn import svm
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import GroupKFold

In [4]:
train_df = pd.read_csv('/Users/sarora/dev/EAGER/data/training/urls/bing-firm-url-train-v5.csv')
train_df

firm  firm_length  \
0              honeywell international inc.            9   
1              honeywell international inc.            9   
2              honeywell international inc.            9   
3              honeywell international inc.            9   
4              honeywell international inc.            9   
5              honeywell international inc.            9   
6                          imds corporation            4   
7                          imds corporation            4   
8                          imds corporation            4   
9                          imds corporation            4   
10                         imds corporation            4   
11                         imds corporation            4   
12             honeywell international inc.            9   
13             honeywell international inc.            9   
14             honeywell international inc.            9   
15             honeywell international inc.            9   
16             honeywell international inc.            9   
17             honeywell international inc.            9   
18                          ziptronix, inc.            9   
19                          ziptronix, inc.            9   
20                          ziptronix, inc.            9   
21                          ziptronix, inc.            9   
22                          ziptronix, inc.            9   
23                          ziptronix, inc.            9   
24                          ziptronix, inc.            9   
25                          ziptronix, inc.            9   
26                        dcg systems, inc.           11   
27                        dcg systems, inc.           11   
28                        dcg systems, inc.           11   
29                        dcg systems, inc.           11   
..                                      ...          ...   
740  longhorn vaccines and diagnostics, llc           33   
741  longhorn vaccines and diagnostics, llc           33   
742  longhorn vaccines and diagnostics, llc           33   
743  longhorn vaccines and diagnostics, llc           33   
744      medicis pharmaceutical corporation           22   
745      medicis pharmaceutical corporation           22   
746      medicis pharmaceutical corporation           22   
747      medicis pharmaceutical corporation           22   
748      medicis pharmaceutical corporation           22   
749      medicis pharmaceutical corporation           22   
750      medicis pharmaceutical corporation           22   
751      medicis pharmaceutical corporation           22   
752               new england biolabs, inc.           19   
753               new england biolabs, inc.           19   
754               new england biolabs, inc.           19   
755                   parion sciences, inc.           15   
756                   parion sciences, inc.           15   
757                   parion sciences, inc.           15   
758                   parion sciences, inc.           15   
759                   parion sciences, inc.           15   
760                   parion sciences, inc.           15   
761                   parion sciences, inc.           15   
762      teledyne scientific & imaging, llc           29   
763      teledyne scientific & imaging, llc           29   
764      teledyne scientific & imaging, llc           29   
765      teledyne scientific & imaging, llc           29   
766      teledyne scientific & imaging, llc           29   
767      teledyne scientific & imaging, llc           29   
768                        zygo corporation            4   
769                        zygo corporation            4   

                                                   url  \
0                           https://www.honeywell.com/   
1                           https://www.honeywell.com/   
2                           https://www.honeywell.com/   
3                           https://www.honeywell.com/   
4                           

In [67]:
# create training and test sets, split on group (k-cross)

# X, y
X = train_df.drop(['firm', 'url', 'name_clnd', 'hit_url', 'outcome'], axis=1)
y = train_df[['outcome']]

# Check how unbalanced we are
display("Outcomes are unbalanced.")
unique, counts = np.unique(y, return_counts=True)
display(dict(zip(unique, counts)))

# Assign gruops based on 'firm'
groups = train_df.groupby('firm').ngroup().values

# Create training and test splits
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
display("Shapes of training and test data.")
display(X_train.shape)
display(X_test.shape)
display (y_train.shape)
display (y_test.shape)

avg_score = np.mean(score_array)
print(avg_score)

'Outcomes are unbalanced.'

{0: 671, 1: 99}

'Shapes of training and test data.'

(515, 7)

(255, 7)

(515, 1)

(255, 1)

In [36]:
# train a few models

names = ["Nearest Neighbors", "Linear SVM", "RBF SVM", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost",
         "Naive Bayes", "SVC", "QDA"]

classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1),
    AdaBoostClassifier(),
    GaussianNB(),
    SVC(gamma=0.001, C=100.), 
    QuadraticDiscriminantAnalysis()]

In [37]:
for name, clf in zip(names, classifiers):
    display (name)
    clf.fit(X_train, np.ravel(y_train))
    y_hat = clf.predict(X_test)
    y_test_numpy = y_test['outcome'].values
    # display(type(y_hat))
    # display(type(y_test_numpy))
    # display(y_hat[0:5])
    # display(y_test_numpy[0:5])
    display (pd.crosstab(y_test_numpy, y_hat, rownames=['True'], colnames=['Predicted'], margins=True))

'Nearest Neighbors'

Predicted    0   1  All
True                   
0          208  16  224
1            6  25   31
All        214  41  255

'Linear SVM'

Predicted    0   1  All
True                   
0          214  10  224
1            1  30   31
All        215  40  255

'RBF SVM'

Predicted    0  1  All
True                  
0          224  0  224
1           26  5   31
All        250  5  255

'Gaussian Process'

Predicted    0   1  All
True                   
0          215   9  224
1            3  28   31
All        218  37  255

'Decision Tree'

Predicted    0   1  All
True                   
0          219   5  224
1            4  27   31
All        223  32  255

'Random Forest'

Predicted    0   1  All
True                   
0          218   6  224
1            6  25   31
All        224  31  255

'Neural Net'

Predicted    0   1  All
True                   
0          218   6  224
1            6  25   31
All        224  31  255

'AdaBoost'

Predicted    0   1  All
True                   
0          219   5  224
1            5  26   31
All        224  31  255

'Naive Bayes'

Predicted    0   1  All
True                   
0          209  15  224
1            1  30   31
All        210  45  255

'SVC'

Predicted    0   1  All
True                   
0          218   6  224
1            2  29   31
All        220  35  255

'QDA'

Predicted    0   1  All
True                   
0          210  14  224
1            1  30   31
All        211  44  255

In [50]:
X = np.array([[5, 2], [3, 4], [1, 2], [3, 4], [5,6], [7,8]])
display(X)
rkf = RepeatedKFold(n_splits=2, n_repeats=3)
for train, test in rkf.split(X):
    print("%s %s" % (train, test))

array([[5, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

[0 1 5] [2 3 4]
[2 3 4] [0 1 5]
[1 2 3] [0 4 5]
[0 4 5] [1 2 3]
[0 2 4] [1 3 5]
[1 3 5] [0 2 4]
